version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=bookstore.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/bookstore
      - DEBUG=1
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    networks:
      - backend
    ports:
      - "5432:5432"
networks:
  backend:
    driver: bridge

volumes:
  postgres_data: